FROM debian:buster
MAINTAINER RRV

ENV VERSION 1.0

RUN apt-get update

# CUrl and software-properties-common
RUN apt-get -y install curl && \
    apt-get -y install software-properties-common

# apt-get update
RUN apt-get update

# Dependencies
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    curl -sL "https://dl.yarnpkg.com/debian/pubkey.gpg" | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add - && \
    echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
    curl -sL https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - && \
    echo "deb https://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list && \
    curl -sL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google.list && \
    curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6616109451BBBF2" | apt-key add - && \
    echo "deb http://packages.linuxmint.com debbie import" | tee /etc/apt/sources.list.d/mint-debbie.list && \
    echo "deb http://security.debian.org/debian-security stretch/updates main" | tee /etc/apt/sources.list.d/stretch-updates.list

# Mongo, NodeJS, Git, SBT, xvfb, FireFox, Chrome
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y nodejs && \
    apt-get install -y gcc g++ make && \
    apt-get install -y mongodb-org && \
    apt-get install -y google-chrome-stable && \
    apt-get install -y git && \
    apt-get install -y sbt && \
    apt-get install -y xvfb && \
    apt-get install -y firefox-esr && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Scala
RUN curl -O -q http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.deb && \
    dpkg -i scala-2.11.5.deb && \
    rm scala-2.11.5.deb

# Gulp, bower
RUN npm install -g gulp bower

# Dirs
RUN mkdir /source
RUN mkdir -p /data/db

ADD project /source/project
ADD build.sbt /source/build.sbt
ADD client/bower.json /source/client/bower.json
ADD client/gulpfile.js /source/client/gulpfile.js
ADD client/package.json /source/client/package.json
ADD client/wct.conf.js /source/client/wct.conf.js
ADD client/test.html /source/client/test.html
ADD run_tests.sh /source/run_tests.sh

# Dependencies
RUN cd /source && sbt update
RUN cd /source/client && npm install && bower install --allow-root --config.interactive=false -s

# Envs
ENV TEST_TYPE "spec"
ENV DOMAIN "http://172.17.42.1"
ENV DISPLAY ":1.0"
ENV DB_HOST localhost

WORKDIR /source
VOLUME ["/source", "/source/target/scala-2.10", "/root/.ivy2/cache", "/data/db"]

CMD ["/source/run_tests.sh"]

EXPOSE 8080
